[package]
name = "haupdown"
version = "0.1.0"
authors = ["James Brown <roguelazer@roguelazer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
clap = "2"
rusqlite = "0.21"
log = "*"
derive_more = "*"
